### ISSUE TITLE
Cant get the bot to run linux

### ISSUE THREAD

**Issue by xblitz151** [Ly-sec/PalBot#21]
Ive installed many bots like this on windows but not on Linux. So i installed the repo, created my discord bot and invited with admin permissions.
Changed the config file with my token and other info. 
When running node . its returning with this error but not sure why? 
Also my node version is 12.22.9

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/PalBot/node_modules/discord.js/src/index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by xblitz151** [comment]
Ive also done on my linux box sudo update/upgrade etc.

**Comment by Peeraboon** [comment]
I also got this problem. Changing nodejs to version 21 fix this.

**Comment by xblitz151** [comment]
> I also got this problem. Changing nodejs to version 21 fix this.

yea working now, how can you stop the bot on linux?

**Comment by xblitz151** [comment]
> > I also got this problem. Changing nodejs to version 21 fix this.
> 
> yea working now, how can you stop the bot on linux?

nvm just control + C i guess

**Comment by xblitz151** [comment]
Do you know if there is a way to add extra ports to the one IP or would i have to run a bot for each pal server?
Being that commas end each line in the config so would something like this work?
"rcon_port": 1111;1234;4444,
"rcon_port": 1111-44444,
or something?

**Comment by xblitz151** [comment]
> I also got this problem. Changing nodejs to version 21 fix this.

Yea seemed to help. Still got issues tho as i posted in the issues area.
